site_name: rbx-ds-cloud
site_url: https://refineddev.github.io/rbx-ds-cloud/

repo_name: rbx-ds-cloud
repo_url: https://github.com/RefinedDev/rbx-ds-cloud

nav:
  - Home: index.md
  - CLI: cli.md
  - Install: install.md
  - Library Documentation: api.md

theme:
  name: material
  include_search_page: false
  search_index_only: true
  language: en
  icon: 
    repo: fontawesome/brands/github
  favicon: imgs/favicon.ico
  logo: imgs/icon.png
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/lightbulb
        name: Go Dark Mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Go Light Mode
    
markdown_extensions:
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences